spring:
  application:
    name : jpa
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123
  jpa:
    show-sql: true

server:
  port : 9090
